-- CreateTable
CREATE TABLE "TB_POINT" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "point" INTEGER NOT NULL DEFAULT 0,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TB_POINT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "TB_POINT_HISTORY" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "point" INTEGER NOT NULL,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TB_POINT_HISTORY_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "TB_POINT_userId_key" ON "TB_POINT"("userId");

-- AddForeignKey
ALTER TABLE "TB_POINT" ADD CONSTRAINT "TB_POINT_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TB_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_POINT_HISTORY" ADD CONSTRAINT "TB_POINT_HISTORY_id_fkey" FOREIGN KEY ("id") REFERENCES "TB_POINT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TB_POINT_HISTORY" ADD CONSTRAINT "TB_POINT_HISTORY_userId_fkey" FOREIGN KEY ("userId") REFERENCES "TB_USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
